name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        DOCKER_USER=${DOCKER_USERNAME:-chaitanya1585}
        docker build -t $DOCKER_USER/ci-cd-demo:latest .

    - name: Login to DockerHub
      if: github.event_name == 'push'
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      if: github.event_name == 'push'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        DOCKER_USER=${DOCKER_USERNAME:-chaitanya1585}
        docker push $DOCKER_USER/ci-cd-demo:latest
