name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/ci-cd-demo:latest .

    - name: Login to DockerHub
      if: github.event_name == 'push'
      run: echo "${{ secrets.dckr_pat_OBNIx6PRCxZd1lmr0Y86REol7sM }}" | docker login -u "${{ secrets.chaitanya1585 }}" --password-stdin

    - name: Push Docker image
      if: github.event_name == 'push'
      run: docker push your-dockerhub-chaitanya1585/ci-cd-demo:latest
